const cars = [
  {
    id: "1",
    brand: "Mercedes-Benz",
    model: "Clase C 220",
    variant: "C 220 d AMG",
    year: 2019,
    mileage: 45000,
    color: "Blanco",
    horsepower: 194,
    fuel: "Diésel",
    transmission: "Automático",
    price: 25900,
    monthlyPrice: 289,
    images: 8,
    currentImage: 1,
    ivaDeductible: true,
    image_url: "/coches/mercedes-benz-clase-c.jpg",
  },
  {
    id: "2",
    brand: "BMW",
    model: "Serie 3 320d",
    variant: "320d Sport",
    year: 2018,
    mileage: 60000,
    color: "Negro",
    horsepower: 190,
    fuel: "Diésel",
    transmission: "Manual",
    price: 23900,
    monthlyPrice: 269,
    images: 7,
    currentImage: 1,
    ivaDeductible: false,
    image_url: "/coches/bmw-serie-3.jpg",
  },
  {
    id: "3",
    brand: "Audi",
    model: "A4 2.0 TFSI",
    variant: "2.0 TFSI",
    year: 2015,
    mileage: 30000,
    color: "Negro",
    horsepower: 190,
    fuel: "Gasolina",
    transmission: "Automático",
    price: 27900,
    monthlyPrice: 299,
    images: 7,
    currentImage: 1,
    ivaDeductible: true,
    image_url: "/coches/audi-a4.jpg",
  },
  {
    id: "4",
    brand: "Porsche",
    model: "911",
    variant: "Carrera S",
    year: 2012,
    mileage: 80000,
    color: "Negro",
    horsepower: 340,
    fuel: "Gasolina",
    transmission: "Automático",
    price: 54900,
    monthlyPrice: 549,
    images: 9,
    currentImage: 2,
    ivaDeductible: false,
    image_url: "/coches/porsche-911.jpg",
  },
  {
    id: "5",
    brand: "Toyota",
    model: "Tacoma",
    variant: "TRD Pro",
    year: 2021,
    mileage: 20000,
    color: "Marrón",
    horsepower: 218,
    fuel: "Gasolina",
    transmission: "Automático",
    price: 31900,
    monthlyPrice: 349,
    images: 5,
    currentImage: 1,
    ivaDeductible: true,
    image_url: "/coches/toyota-tacoma.webp",
  },
  {
    id: "6",
    brand: "Volkswagen",
    model: "Golf 1.5 TSI",
    variant: "1.5 TSI Sport",
    year: 2019,
    mileage: 40000,
    color: "Gris",
    horsepower: 150,
    fuel: "Gasolina",
    transmission: "Manual",
    price: 18900,
    monthlyPrice: 209,
    images: 6,
    currentImage: 1,
    ivaDeductible: false,
    image_url: "/coches/vw-golf.jpg",
  },
  {
    id: "7",
    brand: "SEAT",
    model: "León FR",
    variant: "FR TSI",
    year: 2014,
    mileage: 55000,
    color: "Blanco",
    horsepower: 150,
    fuel: "Gasolina",
    transmission: "Manual",
    price: 15900,
    monthlyPrice: 179,
    images: 6,
    currentImage: 1,
    ivaDeductible: false,
    image_url: "/coches/seat-leon-fr.jpg",
  },
  {
    id: "8",
    brand: "Tesla",
    model: "Model 3",
    variant: "Long Range",
    year: 2022,
    mileage: 15000,
    color: "Blanco",
    horsepower: 351,
    fuel: "Eléctrico",
    transmission: "Automático",
    price: 48900,
    monthlyPrice: 529,
    images: 10,
    currentImage: 3,
    ivaDeductible: true,
    image_url: "/coches/tesla-model-3.jpg",
  },
  {
    id: "9",
    brand: "Audi",
    model: "Q5 2.0 TDI",
    variant: "2.0 TDI Quattro",
    year: 2018,
    mileage: 75000,
    color: "Gris",
    horsepower: 190,
    fuel: "Diésel",
    transmission: "Automático",
    price: 32900,
    monthlyPrice: 369,
    images: 8,
    currentImage: 2,
    ivaDeductible: false,
    image_url: "/coches/audi-q5.webp",
  },
  {
    id: "10",
    brand: "BMW",
    model: "X1 xDrive20d",
    variant: "xDrive20d",
    year: 2016,
    mileage: 90000,
    color: "Gris",
    horsepower: 190,
    fuel: "Diésel",
    transmission: "Automático",
    price: 19900,
    monthlyPrice: 219,
    images: 7,
    currentImage: 1,
    ivaDeductible: false,
    image_url: "/coches/bmw-x1.jpg",
  },
  {
    id: "11",
    brand: "BMW",
    model: "X1 xDrive20d",
    variant: "xDrive20d",
    year: 2021,
    mileage: 40000,
    color: "Gris",
    horsepower: 190,
    fuel: "Diésel",
    transmission: "Automático",
    price: 22000,
    monthlyPrice: 268,
    images: 7,
    currentImage: 1,
    ivaDeductible: false,
    image_url: "",
  },
];


export { cars };
