import type { Car } from "./definitions";

export const cars: Car[] = [
  {
    id: "1",
    brand: "Tesla",
    model: "Model 3",
    variant: "Long Range",
    price: 45990,
    financePrice: Math.round(45990 * 0.96), // 44150
    monthlyPrice: 599,
    fuel: "Eléctrico",
    year: 2023,
    power: 350,
    location: "Madrid",
    condition: "Nuevo",
    rating: 4.9,
    ivaDeductible: true,
    images: ["/coches/tesla-model-3.jpg"],
    currentImage: 0,
    mileage: 0,
    transmission: "Automático",
    color: "Blanco",
    doors: 4,
    features: [
      "Autopilot",
      "Carga rápida",
      "Pantalla táctil",
      "Asientos calefactables",
    ],
    description:
      "Tesla Model 3 Long Range con autonomía de 580km. Equipamiento completo con autopilot, carga rápida y mucho más.",
  },
  {
    id: "2",
    brand: "BMW",
    model: "i4",
    variant: "eDrive40",
    price: 59900,
    financePrice: Math.round(59900 * 0.96), // 57504
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    power: 340,
    location: "Barcelona",
    condition: "Km 0",
    rating: 4.8,
    ivaDeductible: true,
    images: ["/coches/bmw-i4.jpg"],
    currentImage: 0,
    mileage: 1500,
    transmission: "Automático",
    color: "Azul",
    doors: 4,
    features: [
      "BMW iDrive",
      "Asistente de conducción",
      "Sonido Harman Kardon",
      "Techo panorámico",
    ],
    description:
      "BMW i4 eDrive40 con autonomía de 590km. Equipamiento completo con asistente de conducción, sonido Harman Kardon y mucho más.",
  },
  {
    id: "3",
    brand: "Audi",
    model: "e-tron GT",
    variant: "quattro",
    price: 104900,
    financePrice: Math.round(104900 * 0.96), // 100704
    monthlyPrice: 1299,
    fuel: "Eléctrico",
    year: 2022,
    power: 476,
    location: "Valencia",
    condition: "Seminuevo",
    rating: 4.9,
    ivaDeductible: false,
    images: ["/coches/audi-etron-gt.jpg"],
    currentImage: 0,
    mileage: 15000,
    transmission: "Automático",
    color: "Gris",
    doors: 4,
    features: [
      "Tracción quattro",
      "Carga rápida 270kW",
      "Sonido Bang & Olufsen",
      "Asientos deportivos",
    ],
    description:
      "Audi e-tron GT quattro con autonomía de 488km. Equipamiento completo con tracción quattro, carga rápida y mucho más.",
  },
  {
    id: "4",
    brand: "Porsche",
    model: "Taycan",
    variant: "Turbo S",
    price: 189900,
    financePrice: Math.round(189900 * 0.96), // 182304
    monthlyPrice: 2199,
    fuel: "Eléctrico",
    year: 2023,
    power: 761,
    location: "Madrid",
    condition: "Nuevo",
    rating: 5.0,
    ivaDeductible: false,
    images: ["/coches/porsche-taycan.jpg"],
    currentImage: 0,
    mileage: 0,
    transmission: "Automático",
    color: "Rojo",
    doors: 4,
    features: [
      "Porsche Electric Sport Sound",
      "Carga rápida 270kW",
      "Suspensión neumática adaptativa",
      "Porsche Dynamic Chassis Control",
    ],
    description:
      "Porsche Taycan Turbo S con autonomía de 412km. Equipamiento completo con suspensión neumática adaptativa, carga rápida y mucho más.",
  },
  {
    id: "5",
    brand: "Audi",
    model: "A4",
    variant: "2.0 TDI",
    price: 18900,
    financePrice: Math.round(18900 * 0.96), // 18144
    monthlyPrice: 299,  
    fuel: "Diésel",
    year: 2014,
    power: 150,
    location: "Barcelona",
    condition: "Segunda mano",
    rating: 4.5,
    ivaDeductible: false,
    images: ["/coches/audi-a4.jpg"],
    currentImage: 0,
    mileage: 120000,
    transmission: "Manual",
    color: "Gris Plata",
    doors: 4,
    features: [
      "Navegador MMI",
      "Faros Xenón",
      "Sensores de aparcamiento",
      "Volante multifunción",
    ],
    description:
      "Audi A4 2.0 TDI de 150 CV en excelente estado. Equipado con navegador MMI, faros Xenón y sensores de aparcamiento.",
  },
  {
    id: "6",
    brand: "Toyota",
    model: "Tacoma",
    variant: "TRD Sport 4x4",
    price: 34900,
    financePrice: Math.round(34900 * 0.96), // 33504
    monthlyPrice: 499,
    fuel: "Gasolina",
    year: 2019,
    power: 278,
    location: "Sevilla",
    condition: "Seminuevo",
    rating: 4.6,
    ivaDeductible: false,
    images: ["/coches/toyota-tacoma.webp"],
    currentImage: 0,
    mileage: 45000,
    transmission: "Automático",
    color: "Gris Cemento",
    doors: 4,
    features: [
      "Tracción 4x4",
      'Pantalla táctil 8"',
      "Asientos calefactados",
      "Control de descenso",
    ],
    description:
      "Toyota Tacoma TRD Sport 4x4 con motor V6 de 278 CV. Equipado con pantalla táctil de 8 pulgadas, tracción 4x4 y asientos calefactados.",
  },
  {
    id: "7",
    brand: "Porsche",
    model: "911",
    variant: "Carrera S",
    price: 59900,
    financePrice: Math.round(59900 * 0.96), // 57504
    monthlyPrice: 749,
    fuel: "Gasolina",
    year: 2009,
    power: 385,
    location: "Madrid",
    condition: "Segunda mano",
    rating: 4.7,
    ivaDeductible: false,
    images: ["/coches/porsche-911.jpg"],
    currentImage: 0,
    mileage: 90000,
    transmission: "Automático",
    color: "Rojo",
    doors: 2,
    features: [
      "Sistema PCM",
      "Asientos deportivos",
      "Frenos cerámicos PCCB",
      "Suspensión PASM",
    ],
    description:
      "Porsche 911 Carrera S de 2009 con motor bóxer de 385 CV. Equipado con sistema PCM, frenos cerámicos PCCB y suspensión activa PASM.",
  },
  {
    id: "8",
    brand: "Hyundai",
    model: "IONIQ 5",
    variant: "73 kWh AWD",
    price: 52900,
    financePrice: Math.round(52900 * 0.96), // 50784
    monthlyPrice: 649,
    fuel: "Eléctrico",
    year: 2023,
    power: 305,
    location: "Valencia",
    condition: "Nuevo",
    rating: 4.9,
    ivaDeductible: true,
    images: [],
    currentImage: 0,
    mileage: 0,
    transmission: "Automático",
    color: "Gris",
    doors: 5,
    features: [
      "Carga ultrarrápida 350kW",
      "Vehicle-to-Load",
      "Head-up display",
      "Asientos relajación",
    ],
    description:
      "Hyundai IONIQ 5 73 kWh AWD con autonomía de 480km. Equipamiento completo con carga ultrarrápida, Vehicle-to-Load y mucho más.",
  },
  {
    id: "9",
    brand: "Kia",
    model: "EV6",
    variant: "GT-Line AWD",
    price: 59900,
    financePrice: Math.round(59900 * 0.96), // 57504
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    power: 325,
    location: "Barcelona",
    condition: "Km 0",
    rating: 4.8,
    ivaDeductible: true,
    images: [],
    currentImage: 0,
    mileage: 1000,
    transmission: "Automático",
    color: "Negro",
    doors: 5,
    features: [
      "Carga ultrarrápida 350kW",
      "Vehicle-to-Load",
      "Meridian Premium Sound",
      "Asistente de conducción",
    ],
    description:
      "Kia EV6 GT-Line AWD con autonomía de 506km. Equipamiento completo con carga ultrarrápida, Vehicle-to-Load y mucho más.",
  },
  {
    id: "10",
    brand: "Polestar",
    model: "2",
    variant: "Long Range Dual Motor",
    price: 58900,
    financePrice: Math.round(58900 * 0.96), // 56544
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2022,
    power: 408,
    location: "Madrid",
    condition: "Seminuevo",
    rating: 4.7,
    ivaDeductible: false,
    images: [],
    currentImage: 0,
    mileage: 25000,
    transmission: "Automático",
    color: "Blanco",
    doors: 5,
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Polestar 2 Long Range Dual Motor con autonomía de 480km. Equipamiento completo con Google built-in, carga rápida y mucho más.",
  },
  {
    id: "11",
    brand: "Jaguar",
    model: "I-PACE",
    variant: "EV400 HSE",
    price: 79900,
    financePrice: Math.round(79900 * 0.96), // 76704
    monthlyPrice: 899,
    fuel: "Eléctrico",
    year: 2022,
    power: 400,
    location: "Barcelona",
    condition: "Seminuevo",
    rating: 4.6,
    ivaDeductible: true,
    images: [],
    currentImage: 0,
    mileage: 30000,
    transmission: "Automático",
    color: "Gris",
    doors: 5,
    features: [
      "Pivi Pro",
      "Carga rápida 100kW",
      "Meridian 3D Surround Sound",
      "Asientos deportivos",
    ],
    description:
      "Jaguar I-PACE EV400 HSE con autonomía de 470km. Equipamiento completo con Pivi Pro, carga rápida y mucho más.",
  },
  {
    id: "12",
    brand: "Volvo",
    model: "C40",
    variant: "Recharge Twin",
    price: 57900,
    financePrice: Math.round(57900 * 0.96), // 55584
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    power: 408,
    location: "Valencia",
    condition: "Nuevo",
    rating: 4.8,
    ivaDeductible: true,
    images: [],
    currentImage: 0,
    mileage: 0,
    transmission: "Automático",
    color: "Azul",
    doors: 5,
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Volvo C40 Recharge Twin con autonomía de 451km. Equipamiento completo con Google built-in, carga rápida y mucho más.",
  },
  {
    id: "13",
    brand: "Volvo",
    model: "C50",
    variant: "Recharge Twin",
    price: 57900,
    financePrice: Math.round(57900 * 0.96), // 55584
    monthlyPrice: 699,
    fuel: "Eléctrico",
    year: 2023,
    power: 408,
    location: "Valencia",
    condition: "Nuevo",
    rating: 4.8,
    ivaDeductible: true,
    images: [],
    currentImage: 0,
    mileage: 0,
    transmission: "Automático",
    color: "Azul",
    doors: 5,
    features: [
      "Google built-in",
      "Carga rápida 150kW",
      "Harman Kardon Premium Sound",
      "Pilot Assist",
    ],
    description:
      "Volvo C40 Recharge Twin con autonomía de 451km. Equipamiento completo con Google built-in, carga rápida y mucho más.",
  },
];
